### PR TITLE
Feat: Toggle range of checkboxes while pressing shift key

### PR DESCRIPTION
**Pull request by plibither8**
Hi! Great extension :)

This is a feature that I really thought would be useful, I required it myself. I have come up with an implementation in this PR, the code might be very rough - do tell me where to change it.

Thanks!

### CODE REVIEW

**Comment by guytepper** [comment]
Woah, thanks a lot! Great work 🙂 That'd be a super useful feature. 

I've made some small code styling changes. 
Can you please bump the version in the `manifest.json` file to `1.4.0` so I can merge the PR and update the extension?

Some improvements can be made to the range selection mechanism later on - I'll open an issue for that. If you'd like to take responsibility for it, let me know :)

**Comment by plibither8** [comment]
Hi! I took a look at the desired selection mechanism detailed in #9. This looks pretty simple to implement, I'd be happy to take it up.

**Comment by plibither8** [comment]
@guytepper I think I have made it consistent with the mechanism as shown done by 'checkboxes.js'. Please take a look. Thanks :)

**Comment by guytepper** [comment]
Thanks! It almost works perfectly - is it possible to make it uncheck a range of checkboxes, from the last one selected? (same as the behavior in `checkboxes.js`)

**Comment by plibither8** [comment]
Hi, apologies for the delay! I took a look at the code checkboxes.js was using and implement (hopefully) the same mechanism. It'd be great if you could check it out. Thanks!

**Pull request merged**
